// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRijmW46TQ9otkku1VkN1_IUYNj1A_6Ks',
    appId: '1:720990829888:web:a03d75ba22839279b4cea5',
    messagingSenderId: '720990829888',
    projectId: 'wanur-glove',
    authDomain: 'wanur-glove.firebaseapp.com',
    databaseURL: 'https://wanur-glove-default-rtdb.firebaseio.com',
    storageBucket: 'wanur-glove.firebasestorage.app',
    measurementId: 'G-PNZ8D03GK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjgmpqW87wQIMBIuDCGA6nua_IYEeZ_O8',
    appId: '1:720990829888:android:c75267e711708d5fb4cea5',
    messagingSenderId: '720990829888',
    projectId: 'wanur-glove',
    databaseURL: 'https://wanur-glove-default-rtdb.firebaseio.com',
    storageBucket: 'wanur-glove.firebasestorage.app',
  );
}
